import Link from "next/link";
import { LandingPolicyDemo } from "@/components/LandingPolicyDemo";
import { DisabledGitHubLink } from "@/components/DisabledGitHubLink";

const code = `(Decision decision, uint256 permittedAmount, bytes32 reason) =
    ledgerLine.canExecute(assetId, positionId, Action.BORROW, amount);`;

const decisions = [
  ["ALLOW", "The action can execute.", "text-decision-allow"],
  ["LIMIT", "The amount must be adjusted and resubmitted.", "text-decision-limit"],
  ["REVIEW", "Additional conditions need attention.", "text-decision-review"],
  ["BLOCK", "The action is prohibited by policy.", "text-decision-block"],
];

export default function Landing() {
  return (
    <main className="mx-auto flex max-w-7xl flex-col px-5 md:px-10">
      <nav className="glass-nav sticky top-4 z-50 mx-auto flex min-h-16 w-full items-center justify-between rounded-2xl px-4 py-3 md:px-5" aria-label="Primary navigation">
        <Link href="/" className="flex min-w-0 items-center gap-3 font-semibold tracking-tight"><span className="brand-mark" aria-hidden="true"><span /></span><span className="truncate">LedgerLine <span className="text-terminal-muted">/ Core</span></span><span className="hidden rounded-full border border-terminal-border/80 bg-terminal-bg/30 px-2.5 py-1 font-mono text-[9px] font-normal tracking-normal text-terminal-muted sm:inline"><span className="mr-1.5 text-terminal-accent">●</span>v1.0-testbed</span></Link>
        <div className="flex items-center gap-3 text-xs text-terminal-muted md:gap-5"><div className="hidden items-center gap-5 lg:flex"><a href="#product" className="nav-link transition-colors hover:text-terminal-text">Core primitive</a><a href="#architecture" className="nav-link transition-colors hover:text-terminal-text">Architecture</a><a href="#developer" className="nav-link transition-colors hover:text-terminal-text">Docs</a><a href="https://github.com/anjolagithub/ledgerline-cor" target="_blank" rel="noreferrer" className="nav-link transition-colors hover:text-terminal-text">GitHub</a></div><span className="hidden rounded-full border border-terminal-border/70 bg-terminal-bg/25 px-2.5 py-1 font-mono text-[10px] text-terminal-muted xl:inline"><span className="mr-1.5 text-decision-allow">●</span>RPC active</span><Link href="/app" className="glass-cta rounded-xl px-4 py-2.5 text-[10px] font-semibold uppercase tracking-[.12em] text-terminal-text transition-transform hover:-translate-y-0.5 hover:text-terminal-accent">Launch sandbox <span aria-hidden="true">→</span></Link></div>
      </nav>

      <section id="product" className="hero-grid relative grid scroll-mt-8 items-center gap-10 border-b border-terminal-border py-16 md:grid-cols-[.9fr_1.1fr] md:gap-20 md:py-24 lg:py-28">
        <div className="flex flex-col gap-7"><div className="flex items-center gap-3"><span className="eyebrow">Policy infrastructure / 01</span><span className="h-px w-10 bg-terminal-accent" /></div><h1 className="max-w-2xl text-[3.25rem] font-semibold leading-[.94] tracking-[-.065em] sm:text-6xl md:text-7xl lg:text-[5.4rem]">The decision layer for <span className="text-terminal-accent">serious finance.</span></h1><p className="max-w-lg text-lg leading-8 text-terminal-muted">LedgerLine checks the asset, its current state, the position and the requested action — then returns a clear decision before value moves.</p><div className="flex flex-wrap gap-3"><Link href="/app" className="bg-terminal-accent px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-terminal-accent-fg transition-transform hover:-translate-y-0.5">Explore Core <span aria-hidden="true">→</span></Link><a href="#architecture" className="border border-terminal-border px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em] transition-colors hover:bg-terminal-surface">See the model</a></div></div>
        <div className="relative md:pt-4"><span className="demo-index absolute -top-7 right-0 font-mono text-[10px] tracking-[.16em] text-terminal-muted md:top-0">LIVE MODEL / 01</span><LandingPolicyDemo /></div>
      </section>

      <section className="model-strip border-b border-terminal-border py-7 md:py-8"><div className="eyebrow mb-4">Every decision follows the same path</div><div className="flex flex-wrap items-center gap-x-4 gap-y-3 font-mono text-sm md:text-base"><span>ASSET</span><span className="text-terminal-accent">→</span><span>STATE</span><span className="text-terminal-accent">→</span><span>POSITION</span><span className="text-terminal-accent">→</span><span>RISK</span><span className="text-terminal-accent">→</span><span className="text-terminal-text">POLICY</span><span className="text-terminal-accent">→</span><span className="text-terminal-text">ACTION</span></div></section>

      <section className="grid gap-8 border-b border-terminal-border py-24 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Why it exists / 02</p><h2 className="mt-5 max-w-sm text-3xl font-semibold tracking-tight md:text-4xl">A balance and a price are not the whole story.</h2></div><div className="grid gap-10 md:grid-cols-2"><p className="max-w-md text-base leading-8 text-terminal-muted">Tokenized assets introduce state. Lifecycle changes, restrictions, corporate actions and risk conditions can all change whether a financial action should execute.</p><div className="border-l border-terminal-border pl-6 font-mono text-sm leading-9 text-terminal-muted"><div>BALANCE <span className="text-terminal-border">+</span> STATE</div><div>POSITION <span className="text-terminal-border">+</span> RISK</div><div className="text-terminal-text">POLICY <span className="text-terminal-border">→</span> ACTION</div></div></div></section>

      <section id="architecture" className="grid scroll-mt-8 gap-10 border-b border-terminal-border py-24 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">The primitive / 03</p><h2 className="mt-5 max-w-sm text-3xl font-semibold tracking-tight md:text-4xl">One policy layer. Any asset environment.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-terminal-muted">Asset-specific state stays at the edge. Financial policy stays consistent at the core.</p></div><div className="architecture-flow"><div className="flow-node"><span className="eyebrow">Input</span><strong>Asset environment</strong><small>Asset adapter</small></div><span className="flow-arrow">→</span><div className="flow-node flow-core"><span className="eyebrow">Decision engine</span><strong>LedgerLine Core</strong><small>Position · Lifecycle · Risk · Policy</small></div><span className="flow-arrow">→</span><div className="flow-node"><span className="eyebrow">Output</span><strong>Financial action</strong><small>ALLOW · LIMIT · REVIEW · BLOCK</small></div></div></section>

      <section className="grid gap-10 border-b border-terminal-border py-24 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">State matters / 04</p><h2 className="mt-5 max-w-sm text-3xl font-semibold tracking-tight md:text-4xl">When the asset changes, the policy changes with it.</h2></div><div className="state-story"><div><span className="eyebrow">Lifecycle</span><div className="mt-4 font-mono text-2xl">ACTIVE <span className="text-terminal-accent">→</span> RESTRICTED</div></div><div className="state-result"><span className="font-mono text-xs text-terminal-muted">BORROW REQUEST · $100,000</span><strong className="text-decision-block">BLOCK</strong><p>Asset state does not permit this action.</p></div></div></section>

      <section id="developer" className="grid scroll-mt-8 gap-10 border-b border-terminal-border py-24 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Developer surface / 05</p><h2 className="mt-5 max-w-sm text-3xl font-semibold tracking-tight md:text-4xl">A decision protocol, not another dashboard.</h2></div><div className="grid gap-6 md:grid-cols-[1.2fr_.8fr]"><pre className="overflow-x-auto border border-terminal-border bg-terminal-surface2 p-6 text-xs leading-7 text-terminal-muted"><code>{code}</code></pre><div className="grid gap-4 text-sm leading-6 text-terminal-muted">{decisions.map(([name, description, color]) => <p key={name}><span className={`font-mono ${color}`}>{name}</span><br />{description}</p>)}</div></div></section>

      <section className="flex flex-col gap-7 py-24 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">Next action / 06</p><h2 className="mt-5 max-w-2xl text-4xl font-semibold tracking-tight md:text-5xl">Give every financial action a reason.</h2></div><div className="flex gap-3"><Link href="/app" className="bg-terminal-accent px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-terminal-accent-fg">Open Core →</Link><DisabledGitHubLink /></div></section>
    </main>
  );
}
