import Link from "next/link";
import { LandingPolicyDemo } from "@/components/LandingPolicyDemo";
import { DisabledGitHubLink } from "@/components/DisabledGitHubLink";

const code = `(Decision decision, uint256 permittedAmount, bytes32 reason) =\n    ledgerLine.canExecute(assetId, positionId, Action.BORROW, amount);`;

export default function Landing() {
  return (
    <main className="mx-auto flex max-w-7xl flex-col px-5 md:px-10">
      <nav className="flex items-center justify-between border-b border-terminal-border py-6" aria-label="Primary navigation">
        <Link href="/" className="flex items-center gap-3 font-semibold tracking-tight"><span className="grid size-8 place-items-center bg-terminal-accent text-sm font-black text-terminal-accent-fg">L</span><span>LedgerLine <span className="text-terminal-muted">/ Core</span></span></Link>
        <div className="flex items-center gap-6 text-xs text-terminal-muted"><a href="#architecture" className="hidden transition-colors hover:text-terminal-text md:inline">Architecture</a><Link href="/app" className="border border-terminal-border px-4 py-2.5 text-terminal-text transition-colors hover:border-terminal-accent hover:text-terminal-accent">Open console <span aria-hidden="true">↗</span></Link></div>
      </nav>

      <section className="grid-bg relative grid items-center gap-12 border-b border-terminal-border py-20 md:grid-cols-[1fr_.9fr] md:gap-20 md:py-28">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_20%_20%,rgba(255,112,88,.12),transparent_34%)]" />
        <div className="flex flex-col gap-7"><div className="flex items-center gap-3"><span className="eyebrow">Arbitrum Singapore · 2025</span><span className="h-px w-10 bg-terminal-accent" /></div><h1 className="max-w-2xl text-5xl font-semibold leading-[.98] tracking-[-.055em] md:text-7xl">The policy layer for <span className="text-terminal-accent">real-world</span> finance.</h1><p className="max-w-lg text-lg leading-8 text-terminal-muted">LedgerLine turns asset state, position risk, and lifecycle conditions into enforceable onchain decisions.</p><div className="flex flex-wrap gap-3"><Link href="/app" className="bg-terminal-accent px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-terminal-accent-fg transition-transform hover:-translate-y-0.5">Explore Core <span aria-hidden="true">→</span></Link><a href="#architecture" className="border border-terminal-border px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em] transition-colors hover:bg-terminal-surface">How it works</a></div></div>
        <div className="glow"><LandingPolicyDemo /></div>
      </section>

      <div className="grid gap-4 border-b border-terminal-border py-7 text-xs text-terminal-muted md:grid-cols-3"><div><span className="font-mono text-terminal-accent">01</span><span className="ml-3">Asset-aware execution</span></div><div><span className="font-mono text-terminal-accent">02</span><span className="ml-3">Deterministic policy checks</span></div><div><span className="font-mono text-terminal-accent">03</span><span className="ml-3">Built for tokenized markets</span></div></div>

      <section className="grid gap-8 border-b border-terminal-border py-24 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">The problem / 01</p><h2 className="mt-5 max-w-sm text-3xl font-semibold tracking-tight md:text-4xl">Finance is becoming stateful.</h2></div><div className="grid gap-10 md:grid-cols-2"><p className="max-w-md text-base leading-8 text-terminal-muted">A balance and a price are not enough to determine whether a financial action should execute. Lifecycle, restrictions, corporate actions, and risk conditions change the rules.</p><div className="border-l border-terminal-border pl-6 font-mono text-sm leading-9 text-terminal-muted"><div>BALANCE <span className="text-terminal-border">→</span> STATE</div><div>POSITION <span className="text-terminal-border">→</span> RISK</div><div className="text-terminal-text">POLICY <span className="text-terminal-border">→</span> ACTION</div></div></div></section>

      <section id="architecture" className="grid scroll-mt-8 gap-10 border-b border-terminal-border py-24 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">The primitive / 02</p><h2 className="mt-5 max-w-sm text-3xl font-semibold tracking-tight md:text-4xl">One policy layer. Any asset environment.</h2></div><div className="grid gap-4 font-mono text-sm md:grid-cols-[1fr_auto_1fr_auto_1fr] md:items-center"><div className="border border-terminal-border p-5"><span className="text-terminal-muted">INPUT</span><br /><span className="mt-2 inline-block font-sans text-base text-terminal-text">Asset environment</span><br /><span className="text-xs text-terminal-muted">Asset adapter</span></div><span className="text-terminal-accent">→</span><div className="bg-terminal-surface2 p-6"><span className="eyebrow">Core engine</span><div className="mt-3 font-sans text-lg font-semibold">LedgerLine Core</div><div className="mt-3 text-xs leading-6 text-terminal-muted">Position<br />Lifecycle<br />Risk<br />Policy</div></div><span className="text-terminal-accent">→</span><div className="border border-terminal-border p-5"><span className="text-terminal-muted">OUTPUT</span><br /><span className="mt-2 inline-block text-decision-allow">ALLOW</span> / <span className="text-decision-limit">LIMIT</span><br /><span className="text-decision-review">REVIEW</span> / <span className="text-decision-block">BLOCK</span></div></div></section>

      <section className="grid gap-10 border-b border-terminal-border py-24 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Developer surface / 03</p><h2 className="mt-5 max-w-sm text-3xl font-semibold tracking-tight md:text-4xl">A decision protocol, not another dashboard.</h2></div><div className="grid gap-6 md:grid-cols-[1.2fr_.8fr]"><pre className="overflow-x-auto border border-terminal-border bg-terminal-surface2 p-6 text-xs leading-7 text-terminal-muted"><code>{code}</code></pre><div className="text-sm leading-8 text-terminal-muted"><p><span className="text-decision-allow">ALLOW</span> — execute.</p><p><span className="text-decision-limit">LIMIT</span> — reject and resubmit.</p><p><span className="text-decision-block">BLOCK</span> — prohibited by policy.</p></div></div></section>

      <section className="flex flex-col gap-7 py-24 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">Next action / 04</p><h2 className="mt-5 max-w-2xl text-4xl font-semibold tracking-tight md:text-5xl">Make every financial action explainable.</h2></div><div className="flex gap-3"><Link href="/app" className="bg-terminal-accent px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-terminal-accent-fg">Open Core →</Link><DisabledGitHubLink /></div></section>
    </main>
  );
}
